# ============================================================================
# CodeRabbit Configuration for 16-Bit Weather
# ============================================================================
# 
# This file configures AI-powered code review for your PRs.
# Docs: https://docs.coderabbit.ai/configuration/
# ============================================================================

language: en-US

# ----------------------------------------------------------------------------
# REVIEW BEHAVIOR
# ----------------------------------------------------------------------------
reviews:
  # "chill" = less nitpicky, focuses on real bugs not style preferences
  profile: chill
  
  # Global review instructions for all files
  instructions: |
    ## Project: 16-Bit Weather (16bitweather.co)
    
    A retro weather application with authentic 16-bit terminal aesthetics.
    
    ### Tech Stack
    - Next.js 15 (App Router) + React 19
    - TypeScript (strict)
    - Tailwind CSS v4 + shadcn/ui
    - Supabase (auth + database)
    - Sentry (error monitoring)
    - Deployed on Vercel
    
    ### Theme System
    12 visual themes: dark, miami, tron, synthwave84, tokyoNight, dracula,
    cyberpunk, matrix, atari2600, monochromeGreen, 8bitClassic, 16bitSnes
    
    ### Known Issue Patterns (from Sentry)
    1. HYDRATION ERRORS - Most common bug. SSR/client mismatch from:
       - Reading localStorage during render
       - Date/time formatting differences
       - Conditional rendering based on window size
    
    2. INFINITE LOOPS - useEffect with bad dependencies causing:
       - Maximum update depth exceeded
       - setState inside render
    
    ### What NOT to Flag
    - Retro styling (pixelated fonts, CRT effects, scanlines)
    - Terminal-style UI patterns
    - Files in /_archive (legacy, being removed)
    
    ### What TO Flag (Always)
    - Any code that could cause hydration mismatch
    - Missing error handling in API routes
    - useEffect without proper dependencies
    - Direct DOM manipulation in React components
  
  
  # false = CodeRabbit suggests changes but doesn't block merge
  request_changes_workflow: false
  
  # Summary options
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  
  # Disable the poem (yes, it writes poems by default)
  poem: false
  
  # Collapse long walkthrough sections
  collapse_walkthrough: true
  
  # Skip sequence diagrams
  sequence_diagrams: false
  
  # Show which files changed
  changed_files_summary: true
  
  # ----------------------------------------------------------------------------
  # AUTO-REVIEW SETTINGS
  # ----------------------------------------------------------------------------
  auto_review:
    enabled: true
    drafts: false
    base_branches:
      - main
  
  # ----------------------------------------------------------------------------
  # PATH-SPECIFIC INSTRUCTIONS
  # ----------------------------------------------------------------------------
  path_instructions:
    
    # REACT COMPONENTS
    - path: "components/**/*.tsx"
      instructions: |
        ## Priority Checks for React Components
        
        ### 1. HYDRATION SAFETY (Critical - #1 bug source)
        Flag ANY of these patterns that could cause hydration mismatch:
        - `window` or `document` accessed during render without useEffect
        - `localStorage` or `sessionStorage` read during initial render
        - `Date.now()`, `Math.random()`, or `new Date()` in render
        - Conditional rendering based on client-only state
        
        Good pattern:
        ```tsx
        const [mounted, setMounted] = useState(false);
        useEffect(() => setMounted(true), []);
        if (!mounted) return null;
        ```
        
        ### 2. USE CLIENT DIRECTIVE
        - Verify 'use client' is present when using hooks or browser APIs
        
        ### 3. REACT BEST PRACTICES
        - Missing `key` props in `.map()` iterations
        - useEffect with missing dependencies
        - State updates that could cause infinite loops
        
        ### 4. THEME COMPATIBILITY
        - Check that className includes theme-aware classes where needed
        
        ### DO NOT FLAG
        - Intentional retro/pixel aesthetic styling
        - Use of monospace fonts
        - Terminal-style or "boxy" layouts
        - CRT scanline effects or glowing text
    
    # API ROUTES
    - path: "app/api/**/*.ts"
      instructions: |
        ## Priority Checks for API Routes
        
        ### 1. ERROR HANDLING (Required)
        Every route handler MUST have try/catch:
        ```typescript
        export async function GET(request: Request) {
          try {
            // handler logic
            return NextResponse.json(data);
          } catch (error) {
            console.error('[API] Error:', error);
            return NextResponse.json(
              { error: 'Internal server error' }, 
              { status: 500 }
            );
          }
        }
        ```
        
        ### 2. INPUT VALIDATION
        - Query parameters should be validated before use
        
        ### 3. STATUS CODES
        - 400 for bad/missing input
        - 401 for unauthorized
        - 404 for not found
        - 500 for server errors
        
        ### 4. SECURITY
        - No API keys or secrets in responses
    
    # PAGES
    - path: "app/**/page.tsx"
      instructions: |
        ## Priority Checks for Pages
        
        ### 1. METADATA
        - Verify metadata export exists for SEO
        
        ### 2. SSR SAFETY
        - No direct localStorage/window access at module level
        - Dynamic imports for client-only components
        
        ### 3. LOADING STATES
        - Consider if loading.tsx is needed
    
    # LIBRARY CODE
    - path: "lib/**/*.ts"
      instructions: |
        ## Priority Checks for Library Code
        
        ### 1. TYPE SAFETY
        - Flag `any` types - suggest proper types
        - Check for potential null/undefined access
        
        ### 2. ERROR HANDLING
        - Exported functions should handle edge cases
        - Weather API functions need rate limit handling
    
    # TESTS
    - path: "tests/**/*"
      instructions: |
        ## Priority Checks for Tests
        
        ### 1. NO HARDCODED TIMEOUTS
        Flag this pattern:
        ```typescript
        // BAD
        await page.waitForTimeout(2000);
        ```
        
        Suggest:
        ```typescript
        // GOOD
        await expect(element).toBeVisible({ timeout: 15000 });
        ```
        
        ### 2. TEST ISOLATION
        - No shared state between tests
        
        ### 3. MEANINGFUL ASSERTIONS
        - Tests should verify behavior, not just existence
    
    # HOOKS
    - path: "hooks/**/*.ts"
      instructions: |
        ## Priority Checks for Custom Hooks
        
        - Must start with "use" prefix
        - useEffect/useCallback/useMemo deps must be complete
        - Effects with subscriptions need cleanup functions

  # ----------------------------------------------------------------------------
  # FILES TO SKIP
  # ----------------------------------------------------------------------------
  path_filters:
    - "!**/*.lock"
    - "!**/package-lock.json"
    - "!**/.next/**"
    - "!**/node_modules/**"
    - "!**/playwright-report/**"
    - "!**/test-results/**"
    - "!**/_archive/**"
    - "!**/public/fonts/**"

# ----------------------------------------------------------------------------
# CHAT SETTINGS
# ----------------------------------------------------------------------------
chat:
  auto_reply: true

# ----------------------------------------------------------------------------
# KNOWLEDGE BASE
# ----------------------------------------------------------------------------
knowledge_base:
  learnings:
    scope: auto
  opt_out: false

# ----------------------------------------------------------------------------
# TONE & CUSTOM INSTRUCTIONS
# ----------------------------------------------------------------------------
tone_instructions: |
  Be direct and actionable. Focus on bugs that will cause runtime errors,
  not style preferences. This is a retro-themed weather app - don't flag
  intentional aesthetic choices.

early_access: false
