#!/bin/bash
# GitHub Secrets Diagnostic Script

echo "==================================="
echo "GitHub Secrets Configuration Check"
echo "==================================="
echo ""
echo "Please verify you have these EXACT secret names in GitHub:"
echo "(Go to: Settings → Secrets and variables → Actions)"
echo ""
echo "Required for Supabase (must match exactly):"
echo "  ✓ NEXT_PUBLIC_SUPABASE_URL"
echo "  ✓ NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo ""
echo "Required for Weather API:"
echo "  ✓ NEXT_PUBLIC_OPENWEATHER_API_KEY"
echo "    OR"
echo "  ✓ OPENWEATHER_API_KEY"
echo ""
echo "Required for Vercel deployment tests:"
echo "  ✓ VERCEL_TOKEN"
echo "  ✓ VERCEL_ORG_ID"
echo "  ✓ VERCEL_PROJECT_ID"
echo ""
echo "==================================="
echo "Common Issues:"
echo "==================================="
echo ""
echo "1. Secret names are case-sensitive"
echo "   ❌ next_public_supabase_url (wrong)"
echo "   ✅ NEXT_PUBLIC_SUPABASE_URL (correct)"
echo ""
echo "2. No quotes in secret values"
echo "   ❌ \"https://abc.supabase.co\" (wrong)"
echo "   ✅ https://abc.supabase.co (correct)"
echo ""
echo "3. Check for trailing spaces in values"
echo ""
echo "==================================="
echo "Next Steps:"
echo "==================================="
echo ""
echo "1. Run the debug workflow:"
echo "   - Go to GitHub Actions tab"
echo "   - Click 'Debug Environment Variables'"
echo "   - Click 'Run workflow'"
echo ""
echo "2. Check Vercel dashboard:"
echo "   - Go to your Vercel project settings"
echo "   - Check Environment Variables section"
echo "   - Ensure variables are set for Preview"
echo ""
echo "3. If all secrets are correct but still failing:"
echo "   - The updated workflows should fix it"
echo "   - Commit and push the changes"
echo "   - Create a new PR to trigger tests"
