name: 🐛 Bug Report
description: Report a bug or issue with the 16-Bit Weather application
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below with as much detail as possible.

  - type: checkboxes
    id: existing-issues
    attributes:
      label: Pre-submission Checklist
      description: Please check that you've completed these steps before submitting.
      options:
        - label: I searched existing issues and didn't find a duplicate
          required: true
        - label: I have read the README.md and documentation
          required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear description of what you expected to happen.
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened instead of the expected behavior.
      placeholder: What actually happened?
    validations:
      required: true

  - type: input
    id: location-tested
    attributes:
      label: Location Tested
      description: Which city/location were you checking weather for?
      placeholder: e.g., New York, NY or London, UK
    validations:
      required: false

  - type: dropdown
    id: browser
    attributes:
      label: Browser
      description: Which browser are you using?
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Mobile Safari (iOS)
        - Chrome Mobile (Android)
        - Other (specify in additional context)
    validations:
      required: true

  - type: input
    id: browser-version
    attributes:
      label: Browser Version
      description: What version of the browser are you using?
      placeholder: e.g., Chrome 118, Safari 17.0
    validations:
      required: false

  - type: dropdown
    id: device-type
    attributes:
      label: Device Type
      description: What type of device are you using?
      options:
        - Desktop
        - Mobile Phone
        - Tablet
        - Other
    validations:
      required: true

  - type: input
    id: screen-resolution
    attributes:
      label: Screen Resolution
      description: Your screen resolution (if relevant to the bug)
      placeholder: e.g., 1920x1080, 375x667
    validations:
      required: false

  - type: dropdown
    id: theme
    attributes:
      label: Theme Used
      description: Which theme were you using when the bug occurred?
      options:
        - Dark Mode
        - Miami Vice
        - TRON Legacy
        - Atari 2600 (Premium)
        - Terminal Green (Premium)
        - 8-Bit Classic (Premium)
        - 16-Bit SNES (Premium)
        - Not sure
    validations:
      required: false

  - type: textarea
    id: console-errors
    attributes:
      label: Console Errors
      description: Any error messages from the browser console (F12 → Console tab)
      placeholder: |
        Paste any error messages here...
      render: text
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      placeholder: Drag and drop screenshots here or paste image URLs
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional information that might be helpful...
    validations:
      required: false