import { MetadataRoute } from 'next'

export const dynamic = 'force-static'

export default function sitemap(): MetadataRoute.Sitemap {
  const baseUrl = 'https://www.16bitweather.co'
  
  // Major cities for weather pages
  const majorCities = [
    'new-york-ny',
    'los-angeles-ca', 
    'chicago-il',
    'houston-tx',
    'phoenix-az',
    'philadelphia-pa',
    'san-antonio-tx',
    'san-diego-ca',
    'dallas-tx',
    'austin-tx',
    'san-jose-ca',
    'jacksonville-fl',
    'san-francisco-ca',
    'indianapolis-in',
    'columbus-oh',
    'fort-worth-tx',
    'charlotte-nc',
    'detroit-mi',
    'el-paso-tx',
    'seattle-wa',
    'denver-co',
    'washington-dc',
    'memphis-tn',
    'boston-ma',
    'nashville-tn',
    'baltimore-md',
    'oklahoma-city-ok',
    'portland-or',
    'las-vegas-nv',
    'milwaukee-wi',
    'albuquerque-nm',
    'tucson-az',
    'fresno-ca',
    'sacramento-ca',
    'kansas-city-mo',
    'mesa-az',
    'atlanta-ga',
    'omaha-ne',
    'colorado-springs-co',
    'raleigh-nc',
    'miami-fl',
    'virginia-beach-va',
    'oakland-ca',
    'minneapolis-mn',
    'tulsa-ok',
    'arlington-tx',
    'new-orleans-la',
    'wichita-ks',
    'cleveland-oh',
    'tampa-fl',
    'bakersfield-ca',
    'aurora-co',
    'honolulu-hi',
    'anaheim-ca',
    'santa-ana-ca',
    'corpus-christi-tx',
    'riverside-ca',
    'lexington-ky',
    'stockton-ca',
    'st-paul-mn',
    'cincinnati-oh',
    'anchorage-ak',
    'henderson-nv',
    'greensboro-nc',
    'plano-tx',
    'newark-nj',
    'lincoln-ne',
    'buffalo-ny',
    'jersey-city-nj',
    'chula-vista-ca',
    'fort-wayne-in',
    'orlando-fl',
    'st-petersburg-fl',
    'chandler-az',
    'laredo-tx',
    'norfolk-va',
    'durham-nc',
    'madison-wi',
    'lubbock-tx',
    'irvine-ca',
    'winston-salem-nc',
    'glendale-az',
    'garland-tx',
    'hialeah-fl',
    'reno-nv',
    'chesapeake-va',
    'gilbert-az',
    'baton-rouge-la',
    'irving-tx',
    'scottsdale-az',
    'north-las-vegas-nv',
    'fremont-ca',
    'boise-id',
    'richmond-va',
    'san-bernardino-ca',
    'birmingham-al',
    'spokane-wa',
    'rochester-ny',
    'des-moines-ia',
    'modesto-ca',
    'fayetteville-nc',
    'tacoma-wa',
    'oxnard-ca',
    'fontana-ca',
    'columbus-ga',
    'montgomery-al',
    'moreno-valley-ca',
    'shreveport-la',
    'aurora-il',
    'yonkers-ny',
    'akron-oh',
    'huntington-beach-ca',
    'little-rock-ar',
    'augusta-ga',
    'amarillo-tx',
    'glendale-ca',
    'mobile-al',
    'grand-rapids-mi',
    'salt-lake-city-ut',
    'tallahassee-fl',
    'huntsville-al',
    'grand-prairie-tx',
    'knoxville-tn',
    'worcester-ma',
    'newport-news-va',
    'brownsville-tx',
    'overland-park-ks',
    'santa-clarita-ca',
    'providence-ri',
    'garden-grove-ca',
    'chattanooga-tn',
    'oceanside-ca',
    'jackson-ms',
    'fort-lauderdale-fl',
    'santa-rosa-ca',
    'rancho-cucamonga-ca',
    'port-st-lucie-fl',
    'tempe-az',
    'ontario-ca',
    'vancouver-wa',
    'cape-coral-fl',
    'sioux-falls-sd',
    'springfield-mo',
    'peoria-az',
    'pembroke-pines-fl',
    'elk-grove-ca',
    'salem-or',
    'lancaster-ca',
    'corona-ca',
    'eugene-or',
    'palmdale-ca',
    'salinas-ca',
    'springfield-ma',
    'pasadena-ca',
    'fort-collins-co',
    'hayward-ca',
    'pomona-ca',
    'cary-nc',
    'rockford-il',
    'alexandria-va',
    'escondido-ca',
    'mckinney-tx',
    'kansas-city-ks',
    'joliet-il',
    'sunnyvale-ca',
    'torrance-ca',
    'bridgeport-ct',
    'lakewood-co',
    'hollywood-fl',
    'paterson-nj',
    'naperville-il',
    'syracuse-ny',
    'mesquite-tx',
    'dayton-oh',
    'savannah-ga',
    'clarksville-tn',
    'orange-ca',
    'pasadena-tx',
    'fullerton-ca',
    'killeen-tx',
    'frisco-tx',
    'hampton-va',
    'mcallen-tx',
    'warren-mi',
    'west-valley-city-ut',
    'columbia-sc',
    'olathe-ks',
    'sterling-heights-mi',
    'new-haven-ct',
    'miramar-fl',
    'waco-tx',
    'thousand-oaks-ca',
    'cedar-rapids-ia',
    'charleston-sc',
    'visalia-ca',
    'topeka-ks',
    'elizabeth-nj',
    'gainesville-fl',
    'thornton-co',
    'roseville-ca',
    'carrollton-tx',
    'coral-springs-fl',
    'stamford-ct',
    'simi-valley-ca',
    'concord-ca',
    'hartford-ct',
    'kent-wa',
    'lafayette-la',
    'midland-tx',
    'surprise-az',
    'denton-tx',
    'victorville-ca',
    'evansville-in',
    'santa-clara-ca',
    'abilene-tx',
    'athens-ga',
    'vallejo-ca',
    'allentown-pa',
    'norman-ok',
    'beaumont-tx',
    'independence-mo',
    'murfreesboro-tn',
    'ann-arbor-mi',
    'fargo-nd',
    'columbia-mo',
    'south-bend-in',
    'reading-pa',
    'clearwater-fl',
    'yuma-az',
    'pearland-tx',
    'richardson-tx',
    'league-city-tx',
    'wylie-tx',
    'lowell-ma',
    'elgin-il',
    'charleston-wv',
    'woodbridge-nj',
    'chico-ca',
    'rialto-ca'
  ]

  // Static pages
  const staticPages = [
    {
      url: baseUrl,
      lastModified: new Date(),
      changeFrequency: 'daily' as const,
      priority: 1,
    },
    {
      url: `${baseUrl}/about`,
      lastModified: new Date(),
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/cloud-types`,
      lastModified: new Date(),
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/weather-systems`,
      lastModified: new Date(),
      changeFrequency: 'weekly' as const,
      priority: 0.8,
    },
    {
      url: `${baseUrl}/games`,
      lastModified: new Date(),
      changeFrequency: 'weekly' as const,
      priority: 0.7,
    },
  ]

  // Weather city pages
  const weatherPages = majorCities.map(city => ({
    url: `${baseUrl}/weather/${city}`,
    lastModified: new Date(),
    changeFrequency: 'hourly' as const,
    priority: 0.9,
  }))

  return [
    ...staticPages,
    ...weatherPages
  ]
}